version: 2.0.{build}
before_build:
- cmd: >-
    cd src

    nuget restore

    cd ..
build:
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: 52NFtcv+uVrZKBUijhbVkw==
  on:
    branch: master